/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description 用户名（2-50 字符） */
                        username: string;
                        /** @description 密码（6-100 字符） */
                        password: string;
                        /** @description 确认密码 */
                        confirmPassword: string;
                    };
                };
            };
            responses: {
                /** @description 用户注册成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                            /** @description 认证响应 */
                            data: {
                                /** @description 用户信息 */
                                user: {
                                    id: string;
                                    username: string;
                                };
                                /** @description JWT 访问令牌 */
                                accessToken: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description 用户名 */
                        username: string;
                        /** @description 密码 */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description 登录成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                            /** @description 认证响应 */
                            data: {
                                /** @description 用户信息 */
                                user: {
                                    id: string;
                                    username: string;
                                };
                                /** @description JWT 访问令牌 */
                                accessToken: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    /** @description 页码 */
                    page?: number;
                    /** @description 每页数量 */
                    size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 用户列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                            /** @description 用户列表响应 */
                            data: {
                                /** @description 用户列表 */
                                items: {
                                    id: string;
                                    username: string;
                                    /** @description 注册时间（ISO 8601） */
                                    createdAt: string;
                                }[];
                                /** @description 总数 */
                                total: number;
                                /** @description 当前页码 */
                                page: number;
                                /** @description 每页数量 */
                                size: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 用户详情 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                            /** @description 用户信息 */
                            data: {
                                id: string;
                                username: string;
                                /** @description 注册时间（ISO 8601） */
                                createdAt: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 用户已删除 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                            /** @enum {object|null} */
                            data: null;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description 新用户名 */
                        username?: string;
                    };
                };
            };
            responses: {
                /** @description 用户已更新 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                            /** @description 用户信息 */
                            data: {
                                id: string;
                                username: string;
                                /** @description 注册时间（ISO 8601） */
                                createdAt: string;
                            };
                        };
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 用户信息 */
        User: {
            id: string;
            username: string;
            /** @description 注册时间（ISO 8601） */
            createdAt: string;
        };
        /** @description 认证响应 */
        AuthResponse: {
            /** @description 用户信息 */
            user: {
                id: string;
                username: string;
            };
            /** @description JWT 访问令牌 */
            accessToken: string;
        };
        /** @description 用户列表响应 */
        UserListResponse: {
            /** @description 用户列表 */
            items: {
                id: string;
                username: string;
                /** @description 注册时间（ISO 8601） */
                createdAt: string;
            }[];
            /** @description 总数 */
            total: number;
            /** @description 当前页码 */
            page: number;
            /** @description 每页数量 */
            size: number;
        };
        /** @description 更新用户输入 */
        UpdateUserInput: {
            /** @description 新用户名 */
            username?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
